name: CD Platform (Governança)

on:
  workflow_call:
    inputs:
      technology:
        description: Tecnologia da aplicação
        required: true
        type: string

      environment:
        description: Ambiente de deploy (hml | prod)
        required: true
        type: string

jobs:
  governance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validação de ambiente
        run: |
          echo "Validando ambiente: ${{ inputs.environment }}"

          if [[ "${{ inputs.environment }}" != "hml" && "${{ inputs.environment }}" != "prod" ]]; then
            echo "Ambiente inválido!"
            exit 1
          fi

      - name: Governança de deploy
        run: |
          echo "Governança de CD executada"
          echo "Tecnologia: ${{ inputs.technology }}"
          echo "Ambiente: ${{ inputs.environment }}"

  deploy-node:
    if: inputs.technology == 'node'
    needs: governance
    uses: teddy-platform-poc/platform-github-actions/.github/workflows/cd-ecs-node.yml@main
    with:
      environment: ${{ inputs.environment }}

  deploy-java:
    if: inputs.technology == 'java'
    needs: governance
    uses: teddy-platform-poc/platform-github-actions/.github/workflows/cd-ecs-java.yml@main
    with:
      environment: ${{ inputs.environment }}

  deploy-python:
    if: inputs.technology == 'python'
    needs: governance
    uses: teddy-platform-poc/platform-github-actions/.github/workflows/cd-ecs-python.yml@main
    with:
      environment: ${{ inputs.environment }}
