name: CD Platform (Governança)

on:
  workflow_call:
    inputs:
      technology:
        description: Tecnologia da aplicação (node | java | python)
        required: true
        type: string

      environment:
        description: Ambiente de deploy
        required: true
        type: string

jobs:
  governance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validação de ambiente
        run: |
          echo "Validando ambiente informado: ${{ inputs.environment }}"

          if [[ "${{ inputs.environment }}" != "hml" && "${{ inputs.environment }}" != "prod" ]]; then
            echo "Ambiente inválido!"
            exit 1
          fi

      - name: Governança de deploy
        run: |
          echo "Executando validações de governança de CD"
          echo "Tecnologia: ${{ inputs.technology }}"
          echo "Ambiente: ${{ inputs.environment }}"

  deploy:
    needs: governance
    uses: teddy-platform-poc/platform-github-actions/.github/workflows/cd-ecs-${{ inputs.technology }}.yml@main
    with:
      environment: ${{ inputs.environment }}
